version: "3.7"
services:
    my-backend:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 3001:3001
    my-database:
      build:
         context: .
         dockerfile: Dockerfile.mongo
      ports:
         - 27017:27017